# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A personal Website for Personal Problems
email: Nicktv99@Live.com
description: > # this means to ignore newlines until "baseurl:"
  This website was all a test to see if I could actually publish a website using github. Look what we've got here. A website
  that I actually published using github.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Missing link
github_username:  Sharpshot0O7

# Build settings
markdown: kramdown
